### ISSUE TITLE
Using Rancher Host Labels ??

### ISSUE THREAD

**Issue by lolziac** [cdrx/rancher-gitlab-deploy#11]
I tried the tool and it worked perfect, great job.

I just need to make this work with Rancher host labels, I couldn't find a way to achieve this.
Every time I do an upgrade the tool/Rancher chooses a random host do pull the image, and we would like to manage the deployment with rancher labels, so we can deploy on the desired hosts only by using:
io.rancher.scheduler.affinity:host_label: app=true

Is there any way I can achieve this with this image ???

**Comment by cdrx** [comment]
When you first deploy the service, in Rancher, you set the scheduling rules.

When rancher-gitlab-deploy upgrades the service, the rules are not removed, so the upgraded service will be deployed on systems with app=true. 

Do you see a different behaviour?
