### ISSUE TITLE
Add --env-variable to options

### ISSUE THREAD

**Issue by czende** [cdrx/rancher-gitlab-deploy#12]
Is there a way to pass environment variable to upgraded service? Upgraded services have same variables, but I have to i.e. change RELEASE_VERSION after service upgrade.

**Comment by cdrx** [comment]
There isn't any functionality to do this currently, but I would accept a PR with it in.

Why not bake the RELEASE_VERSION into the image with in the Dockerfile? You could use `--build-args`

**Comment by czende** [comment]
Thank you, I did not know about this option.

**Comment by cdrx** [comment]
I think something like:

```
ARG VERSION
ENV RELEASE_VERSION $VERSION
```

`docker build --build-arg VERSION=1.0.0`

should allow you to put the build arg into a persisted environment variable
