### ISSUE TITLE
Blue-Green deployement strategy

### ISSUE THREAD

**Issue by bigfoot90** [cdrx/rancher-gitlab-deploy#14]
Blue/Green deployement strategy
=================
This is feature request.

With blue-Green deployement strategy I have **2 stacks** (say `stack_a` and `stack_b`) plus a reverse-proxy container that swaps beetween `stack_a` and `stack_b`.

The **green** stack is the stable version *(initially `stack_a`)*.
While the **blue** stack is the development version *(initially `stack_a`)*.

The stack where to deploy is determined at runtime by reading the reverse-proxy current status with this command: `docker exec -t proxy_container /status.sh`.

After the deploy we can manually swap the **blue/green** in our reverse-proxy.

After the swap the **green** stack is `stack_b`, and the **blue** stack is `stack_a`.

I'm awaiting your considerations, opinions, questions or suggestions.
Thanks for everyone.

**Comment by cdrx** [comment]
I think you could probably use `rancher-gitlab-deploy` to help with this as part of a wider system, but I don't think this functionality belongs in this project directly. The scope of the tool is just to push containers from GitLab into Rancher. 

You can guide `rancher-gitlab-deploy` to update `stack_a` or `stack_b` by using the `--stack` argument.

**Comment by bigfoot90** [comment]
Do you know how can I run `/status.sh` on container from inside gitlab? maybe using some external tool?

**Comment by cdrx** [comment]
I'm not sure, sorry.

**Comment by cdrx** [comment]
Maybe ask the question on the Rancher forums.
