### ISSUE TITLE
Feature request: zero-downtime upgrade

### ISSUE THREAD

**Issue by chvanikoff** [cdrx/rancher-gitlab-deploy#19]
Hi, thanks for the tool - it comes really handy and works great out of the box with minimal setup required, exactly how it should.
But unfortunately, it doesn't provide zero-downtime upgrade feature (--start-before-stopped is a bit different). For me it seems it can be easily done with this tool, following this strategy for example:
- stack must have service alias "SERVICENAME-alias" for the service to be upgraded
- when upgrade is requested, add new service like "SERVICENAME-upgraded"
- add the "SERVICENAME-upgraded" to "SERVICENAME-alias" links
- perform some kind of check against "SERVICENAME-upgraded" to ensure it have started (this seems tricky since different services require different checks)
- remove original SERVICENAME from SERVICENAME-alias
- rename SERVICENAME-upgraded to just SERVICENAME

**Comment by cdrx** [comment]
I agree this would be a nice feature but it should be implemented in Rancher itself and exposed through the API. I don't think the scope of this tool should be expanded to support operations that Rancher itself doesn't not supply. 

Perhaps file an issue on their Github repo requesting this feature. 

Thanks!
