### ISSUE TITLE
No healthy hosts meet the resource constraints: ports

### ISSUE THREAD

**Issue by ghost** [cdrx/rancher-gitlab-deploy#21]
Dear,

I have on Rancher a stack and service with the same names as the gitlab group and project.
So my gitlab-ci looks like:
`deploy:
  image: cdrx/rancher-gitlab-deploy:latest
  stage: deploy
  only:
    - develop
  script:
    - upgrade`

But when this stage of the pipeline runs i get the following error on rancher:
`middleware (Failed to allocate instance [container:1i451]: Bad instance [container:1i451] in state [error]: Allocation failed: No healthy hosts meet the resource constraints: [ports: [8082:8082/tcp], ResourceType: instanceReservation, Amount: 1]) `

Is this because of the way i created the service (with rancher UI 'Add service')?
Can someone help? This is quite important in our setup.

kind regards,
Thomas

**Comment by cdrx** [comment]
Can you upgrade the service in Rancher UI manually?

**Comment by DomiStyle** [comment]
Can this issue be reopened? I'm experiencing the same right now and I also found the reason.

The message I'm getting is:
``Failed to allocate instance [container:1i87]: Bad instance [container:1i87] in state [error]: Allocation failed: needs host with label name: node01 and resource constraints: [3000:3000/tcp portReservation, 1 instanceReservation]``

After a while it will upgrade anyway but it will sit there doing nothing for about 30 seconds with the message above before actually upgrading.

I would assume @neanex only has one node while I only have one node with the label name=node01. I tried adding another host with label name=node01 and the upgrade worked just fine - swapping back and forth between both nodes with every upgrade.

Upgrades from the UI work as expected.

**Comment by cdrx** [comment]
I think you need the `--no-start-before-stopping` flag, because you can only bind one container to port 3000 at a time.

**Comment by DomiStyle** [comment]
That worked, thanks.

Shouldn't this be the default option though since it is in the UI?

**Comment by cdrx** [comment]
Yep! It should, I agree. 

I tried to map the defaults to the same as Rancher but must have missed this one, I'll change it for the next release.

**Comment by cdrx** [comment]
@DomiStyle I've changed the default for the next release to match Rancher's default behaviour, thanks
