### ISSUE TITLE
Command to execute commands into containers

### ISSUE THREAD

**Issue by kariae** [cdrx/rancher-gitlab-deploy#23]
This is a feature request,

I don't know if this is out of the scope of the project, but most of the projects deployed needs to run some commands after the deployment, for example, [Symfony](http://symfony.com/) needs to update database schema ...

The actual Rancher API handle this using [containerExec](https://docs.rancher.com/rancher/v1.6/en/api/v2-beta/api-resources/containerExec/) ressource.

I can work on that !

**Comment by cdrx** [comment]
Personally, I would do DB migrations etc in an entry point for the container, but if you want to write the code to add an extra command to run after the upgrade I'll gladly accept the PR 👍
