### ISSUE TITLE
Force an Upgrade

### ISSUE THREAD

**Issue by aslafy-z** [cdrx/rancher-gitlab-deploy#28]
I could use a `--force-upgrade` option which would allow me to upgrade even a unhealthy service. In fact, some images pushed by my CI might not be working all the time. I seen that `inactive` services can also  be upgraded. Maybe the option could stop the service and then upgrade it ?
It would be great! Currently I have to get the service healthy by hand in the rancher UI, which is annoying..

**Comment by cdrx** [comment]
I don't think this is possible, sorry. If you can't upgrade it from inside Rancher unless its healthy, then the API won't be able to either.
