### ISSUE TITLE
Question : After upgrade, container created on another host

### ISSUE THREAD

**Issue by Segfaultd** [cdrx/rancher-gitlab-deploy#30]
Hello,

Thanks for your amazing script, got a little question.
After auto deploy, new container is created on another host (multi-nodes rancher config) so my backend URL is changing at each deploy.

Is there a way to upgrade on the same node than the previous container ?

Thanks!

**Comment by cdrx** [comment]
You'll need to either setup a Rancher load balancer in front of your service, use labels to control which hosts the service can be placed on, or pin the service to one host with Rancher's scheduling rules. All of these are covered in the Rancher documentation -- thats the best place to look.
