### ISSUE TITLE
Version-tagged images on Docker Hub

### ISSUE THREAD

**Issue by bradjones1** [cdrx/rancher-gitlab-deploy#32]
First off, thanks so much for this project! Rancher and GitLab work great together, but it's nice not to have to maintain the docker-compose/rancher-compose files inside the project in order to upgrade, especially since the Rancher Compose format doesn't always track with the UI features as they get introduced.

I'm wondering if you'd be open to adjusting your build process to tagging versioned images, in addition to `latest`? Just so we can pin to a specific version for predictable runs?

Thanks!

**Comment by cdrx** [comment]
I've never seen the point personally, but you are not the first to ask for this -- I've added version number tagged builds to Docker Hub 👍
