### ISSUE TITLE
Pre/post deploy hooks

### ISSUE THREAD

**Issue by mbajur** [cdrx/rancher-gitlab-deploy#4]
Hi there!

I'm not sure if that's even possible but i was thinking that it would be awesome to run a set of commands as a pre/post deploy hooks of rancher-gitlab-deploy. 

For example - rails apps needs to run a `$ rake db:migrate` to check if there are any pending database migration and if there are, run them. Right now, i need to do this step manually which kinda sucks. Implementin such feature ins rancher-gitlab-deploy would make this way easier.

Thanks!

**Comment by cdrx** [comment]
Could you put them in a Docker entry point script?

That's what I do with (Django) database migrations and that way they get applied even if I do a manual service upgrade in Rancher.
