### ISSUE TITLE
Error: Got unexpected extra argument

### ISSUE THREAD

**Issue by cylim** [cdrx/rancher-gitlab-deploy#41]
I have no idea why this error occurred, I tried to run it on my device, it doesn't have any error, but when I run it at Gitlab, it doesn't work.

CI error log
```
$ upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service $RANCHER_SERVICE --new-image $IMAGE_TAG --finish-upgrade
Usage: upgrade [OPTIONS]

Error: Got unexpected extra argument (registry.gitlab.com/<GROUP>/<REPO>:<TAG>)
ERROR: Job failed: exit code 2
```

gitlab-ci.yml
```
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

deploy_staging_api:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  only:
    - test/staging
  script:
    - upgrade
      --environment $RANCHER_ENVIRONMENT
      --stack $RANCHER_STACK
      --service $RANCHER_SERVICE
      --new-image $IMAGE_TAG
      --finish-upgrade
```

**Comment by cylim** [comment]
It is my mistakes, I forget the set the environment name in the gitlab-ci files for getting the right variables for the environment, stack and service 🤣

**Comment by rtorrero** [comment]
@cylim what I do to avoid this is to set Rancher env vars for the whole group on Gitlab (rather than doing it per-project). Groups are a new feature on Gitlab, if you don't have it, just upgrade to the latest.

This way, you set it once for all the projects belonging to the same group (even if you add new projects afterwards)

**Comment by cylim** [comment]
@rtorrero didn't notice your command earlier. The environment name I forgot is belonged to GitLab environment instead of Rancher.

In Rancher, I am using the environment to separate the `development`, `testing`, `staging` and `production`. I am not sure whether this is a good practice, it seems to be the best practice I can come out with.
