### ISSUE TITLE
What about rollback if upgrade fail ?

### ISSUE THREAD

**Issue by Royalsspirit** [cdrx/rancher-gitlab-deploy#46]
Hello,

First, this project is very good. First time i try, all work well even in production. i appreciate it :)

I use image rancher-gitlab-deploy image with gitlab-ci to upgrade my project in rancher.

I'im wondering if we can add some optionnal parameter to rollback if upgrade fail, somethings like --rollback.

In rancher api, it's available. [See](http://rancher.com/docs/rancher/v1.4/en/api/v2-beta/api-resources/stack/#rollback) 

If you need some others informations, i'm here.

**Comment by cdrx** [comment]
This has been implemented with the new `--rollback-on-error/--no-rollback-on-error` options
