### ISSUE TITLE
Download new docker image with same tag

### ISSUE THREAD

**Issue by lgaticaq** [cdrx/rancher-gitlab-deploy#48]
If the image that is specified has the same tag (example ":testing") use the option "Always pull image before creating"

**Comment by cdrx** [comment]
This flag is already set; `rancher-gitlab-deploy` will pull the latest copy of the image, even if you are updating the same tag.

Do you see otherwise?

**Comment by lgaticaq** [comment]
A few days ago it did not happen that way. I'll see if it works for me in the next deployment. Thank you.
