### ISSUE TITLE
¿How change default options?

### ISSUE THREAD

**Issue by Jose3212** [cdrx/rancher-gitlab-deploy#52]
Hi! I deploy the containers using the upgrade command but I would be interested in using the option  --start-before-stopping, that I see is set false by default. I run the upgrade like this: 

`upgrade --stack MyStack --service phpfpm --finish-upgrade --sidekicks --new-sidekick-image phpfpm-app $CONTAINER_RELEASE_IMAGE`

If I add the option in there I got this and fails:

> $ upgrade --stack MyStack --service phpfpm --finish-upgrade --sidekicks --new-sidekick-image --start-before-stopping phpfpm-app $CONTAINER_RELEASE_IMAGE
Usage: upgrade [OPTIONS]

How can I change that option?

**Comment by cdrx** [comment]
`--new-sidekick-image` takes arguments but you haven't specified any

**Comment by Jose3212** [comment]
Thank you now it works fine!
