### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by gizmotronic** [cdrx/rancher-gitlab-deploy#66]
My Rancher environment is completely migrated to Rancher 2 at this point, and I'm now using an image based on `bitnami:kubectl` in my GitLab CI jobs to deploy updated applications. I may never have gotten to this point without the work you did to simplify deployments to Rancher 1.x environments, though, so I just wanted to send a heartfelt thank you for that, and best wishes for whatever projects you're working on now.

**Comment by cdrx** [comment]
I'm glad it was useful to you 👍
