### ISSUE TITLE
Wait for migrator service

### ISSUE THREAD

**Issue by krajcikondra** [cdrx/rancher-gitlab-deploy#68]
Hi, 

I have pipeline with three steps:

1. run maintenance mode
2. migrate db - Started once service
3. run production mode back

I am facing to problem with waiting for migrator in step 2. 

Following command:

`upgrade --environment Staging --stack $STACK_NAME --service migrator --new-image myImage:$APP_VERSION --finish-upgrade`

run migrations which usually running 1-2 minutes but pipeline dont wait for migrations done and start step 3 (run production mode).

It is possible wait for migrator and then continue to next step?

**Comment by rtyshyk** [comment]
I suppose you are talking about it, see  --wait-for-upgrade-to-finish / --no-wait-for-upgrade-to-finish
+ make sure that you have proper health checks in rancher
