### ISSUE TITLE
revert upgrade on failure/timeout

### ISSUE THREAD

**Issue by nick-traeger** [cdrx/rancher-gitlab-deploy#8]
It would be nice if it reverts the upgrade on a failure / after the timeout

**Comment by cdrx** [comment]
If the upgrade fails, Rancher will revert it if you supply the `--start-before-stopping` option. 

Rancher will keep the old containers around until the new one passes a health check.

**Comment by nick-traeger** [comment]
Thank you for the tipp. But had now a similar problem. The upgrade runs into a timeout and on the next run it detects the "not active" state. So it would be nice if it reverts the upgrade after timeout or failure.

**Comment by cdrx** [comment]
Which bit actually times out -- is it that Rancher can't run the upgrade? Do you get the same failure in the Rancher UI itself?

**Comment by nick-traeger** [comment]
The upgrade took longer then the timeout setting, so the deploy-script stopped. Rancher then finished the upgrade after some time, but the script detected the "upgrade finish" state on the next run and quit.

**Comment by cdrx** [comment]
Thanks. Can you try increasing the timeout with `--upgrade-timeout 300` or something? 

If the tool tries to upgrade a service that hasn't been marked as upgrade finished it'll finish the upgrade first, but only up to the the amount of seconds in `upgrade-timeout`

**Comment by cdrx** [comment]
Actually, maybe 600 seconds, as 300 is the default :)

**Comment by nick-traeger** [comment]
Yeah, i currently increased it. But it could prevent some failure in the future, if we have an flag to let the deploy script revert an failed upgrade ;)
